# -*- coding: utf-8 -*-
"""Assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmwjSvqR8fNMwfNjaZIk37TkYyjngBO7
"""



def check_intern_eligibility(age,percentage):
  if(age>=18):
    if(percentage>=60):
      return "eligible: due to above 60%"
    else:
      return "not eligible: due to below 60%"
  else:
    return "not eligible: ue to below 18 age"
age=int(input("enter age: "))
percentage=int(input("enter percentage: "))
print(check_intern_eligibility(age,percentage))