# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VF-noupVWhVg5u-K6MVzLxt4UHjEzaU
"""

Amount=int(input("Enter the amount:"))
if Amount>0:
  print("valid")
else:
  print("not valid")