# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VF-noupVWhVg5u-K6MVzLxt4UHjEzaU
"""

opening_stock=[50,35,45,56]
closing_stock=[43,63,45,62]
for i in range(len(opening_stock)):
    if closing_stock[i]>opening_stock[i]:
       print("product",i+1,"stock increased")
    elif closing_stock[i]<opening_stock[i]:
        print("product",i+1,"stock decrease")
    else:
        print("product",i+1,"stock remain same")