# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxptU1nZRs3SdX2r-MTEjKHeCsHFaF6v
"""

Item_price=[300,230,450,300,500,600]
Total_order_values=sum(Item_price)
average_order_value=Total_order_values/len(Item_price)
print("Total_order_values:",Total_order_values)
print("average_order_value:",average_order_value)

