# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VF-noupVWhVg5u-K6MVzLxt4UHjEzaU
"""

student_course={
    "Asha":"Python",
    "Ravi":"Data Analysis",
    "Neha":"AI"
    }
print("students name:")
for student in student_course:
  print(student)
print("courses name:")
for course in student_course.values():
  print(course)
name=input("enter student name")
if name in student_course:
  print(student_course[name])
else:
  print("student not found")

Distance=int(input("enter the distance in km"))
if Distance<=5:
  print("Local")
elif 6<=Distance<=20:
  print("City")
else:
  print("outstation")

student_score=[45,34,67,54,97]
total=sum(student_score)
average_score=total/len(student_score)
count_above_average=0
for score in student_score:
  if score>average_score:
    count_above_average+=1
print("Scores",student_score)
print("Total Score:",total)
print("Average Score:",average_score)
print("count of scores above average:",count_above_average)