# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxptU1nZRs3SdX2r-MTEjKHeCsHFaF6v
"""

Products={
    "Laptop":"Electronics",
    "Chair":"Furnitures",
    "Mobile":"Electronics"
}
for Product in Products.keys():
  print("products name:",Product)

for category in Products.values():
  print("Produst categories:",category)
print(len(Products))