# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VF-noupVWhVg5u-K6MVzLxt4UHjEzaU
"""

student_course={
    "Asha":"Python",
    "Ravi":"Data Analysis",
    "Neha":"AI"
    }
print("students name:")
for student in student_course:
  print(student)
print("courses name:")
for course in student_course.values():
  print(course)
name=input("enter student name")
if name in student_course:
  print(student_course[name])
else:
  print("student not found")