# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxptU1nZRs3SdX2r-MTEjKHeCsHFaF6v
"""

website_visitors=[230,34,340,235,600,300,900]
print("Highest Traffic",max(website_visitors))
print("Lowest Traffic",min(website_visitors))